import json
import uuid

notebook_path = '/Users/yanivnaggar/Desktop/Spring 2026/IS/BCI-project/data_cleaning_analysis.ipynb'
with open(notebook_path, 'r') as f:
    nb = json.load(f)

has_step_11 = any("Step 11:" in "".join(c.get('source', [])) for c in nb['cells'])
if not has_step_11:
    markdown_cell = {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### Step 11: Event-Driven Discrete Command Decoder\n",
            "\n",
            "Moving from continuous accuracy metrics to an online, discrete command simulator. Requirements:\n",
            "1. **Two-Stage Decoder:** Intent Gate (Norm vs Active) -> Direction Classifier (Left vs Right).\n",
            "2. **Contralateral Asymmetry Features:** Used for discrete direction classification.\n",
            "3. **Debouncing Logic:** Require K consecutive windows above threshold, implement a cooldown period after a trigger, and use majority voting.\n",
            "4. **Simulation Metrics:** Event-level precision/recall, latency, and false trigger rate per minute on held-out test groups."
        ]
    }

    code_cell = {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "from sklearn.model_selection import GroupShuffleSplit\n",
            "from sklearn.ensemble import RandomForestClassifier\n",
            "from sklearn.pipeline import Pipeline\n",
            "from sklearn.preprocessing import StandardScaler\n",
            "import numpy as np\n",
            "import pandas as pd\n",
            "import matplotlib.pyplot as plt\n",
            "from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay\n",
            "\n",
            "# 1. Extract 1s sliding windows for ALL classes to build the Intent Gate\n",
            "feats_norm_lr, labels_norm_lr, groups_norm_lr, next_id = sliding_window_extraction_grouped(trials_norm_lr, 'Norm', next_id, is_norm=True)\n",
            "feats_norm_hr, labels_norm_hr, groups_norm_hr, next_id = sliding_window_extraction_grouped(trials_norm_hr, 'Norm', next_id, is_norm=True)\n",
            "feats_repeated, labels_repeated, groups_repeated, next_id = sliding_window_extraction_grouped(trials_repeated, 'Repeated', next_id)\n",
            "\n",
            "# Combine all features\n",
            "all_features = feats_left + feats_right + feats_repeated + feats_norm_lr + feats_norm_hr\n",
            "all_labels = labels_left + labels_right + labels_repeated + labels_norm_lr + labels_norm_hr\n",
            "all_groups = groups_left + groups_right + groups_repeated + groups_norm_lr + groups_norm_hr\n",
            "\n",
            "df_all = pd.DataFrame(all_features)\n",
            "y_all = np.array(all_labels)\n",
            "groups_all = np.array(all_groups)\n",
            "\n",
            "# Add Asymmetry Features back to df_all\n",
            "df_all['C3_C4_Mu_Diff'] = df_all['Channel_1_Mu_Power'] - df_all['Channel_3_Mu_Power']\n",
            "df_all['C4_C3_Mu_Diff'] = df_all['Channel_3_Mu_Power'] - df_all['Channel_1_Mu_Power']\n",
            "df_all['Mu_Asymmetry_Ratio'] = (df_all['Channel_1_Mu_Power'] - df_all['Channel_3_Mu_Power']) / (df_all['Channel_1_Mu_Power'] + df_all['Channel_3_Mu_Power'] + 1e-6)\n",
            "df_all['C3_C4_Beta_Diff'] = df_all['Channel_1_Beta_Power'] - df_all['Channel_3_Beta_Power']\n",
            "df_all['C4_C3_Beta_Diff'] = df_all['Channel_3_Beta_Power'] - df_all['Channel_1_Beta_Power']\n",
            "\n",
            "X_all = df_all.values\n",
            "y_intent = np.array(['Norm' if l == 'Norm' else 'Active' for l in y_all])\n",
            "\n",
            "# 2. Train/Test Split (Grouped by original trial)\n",
            "gss = GroupShuffleSplit(n_splits=1, test_size=0.25, random_state=42)\n",
            "train_idx, test_idx = next(gss.split(X_all, y_all, groups_all))\n",
            "\n",
            "X_train, X_test = X_all[train_idx], X_all[test_idx]\n",
            "y_train_intent, y_test_intent = y_intent[train_idx], y_intent[test_idx]\n",
            "y_train_dir, y_test_dir = y_all[train_idx], y_all[test_idx]\n",
            "groups_train, groups_test = groups_all[train_idx], groups_all[test_idx]\n",
            "\n",
            "# 3. Train Stage A: Intent Gate\n",
            "intent_clf = Pipeline([\n",
            "    ('scaler', StandardScaler()),\n",
            "    ('classifier', RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced'))\n",
            "])\n",
            "intent_clf.fit(X_train, y_train_intent)\n",
            "\n",
            "# 4. Train Stage B: Direction Classifier (Trained ONLY on active Direction records)\n",
            "# We only train direction on Left and Right (Ignoring Repeated/Norm for the Direction model)\n",
            "dir_train_mask = np.isin(y_train_dir, ['Left', 'Right'])\n",
            "X_train_dir = X_train[dir_train_mask]\n",
            "y_train_dir_filtered = y_train_dir[dir_train_mask]\n",
            "\n",
            "direction_clf = Pipeline([\n",
            "    ('scaler', StandardScaler()),\n",
            "    ('classifier', RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced'))\n",
            "])\n",
            "direction_clf.fit(X_train_dir, y_train_dir_filtered)\n",
            "\n",
            "print(\"Models Trained Successfully on 75% Grouped Split.\")\n",
            "\n",
            "# 5. Online Decoder Simulator\n",
            "class DiscreteDecoder:\n",
            "    def __init__(self, intent_model, direction_model, t_active=0.5, k_consecutive=2, cooldown_windows=4, m_majority=3):\n",
            "        self.intent_model = intent_model\n",
            "        self.direction_model = direction_model\n",
            "        self.t_active = t_active\n",
            "        self.k_consecutive = k_consecutive\n",
            "        self.cooldown_windows = cooldown_windows\n",
            "        self.m_majority = m_majority\n",
            "        \n",
            "        self.history_active = []\n",
            "        self.history_direction = []\n",
            "        self.cooldown_counter = 0\n",
            "        \n",
            "    def process_window(self, features):\n",
            "        if self.cooldown_counter > 0:\n",
            "            self.cooldown_counter -= 1\n",
            "            self.history_active.append(False)\n",
            "            return \"NONE\"\n",
            "            \n",
            "        p_active = self.intent_model.predict_proba(features.reshape(1, -1))[0]\n",
            "        active_idx = list(self.intent_model.classes_).index('Active')\n",
            "        is_active = p_active[active_idx] >= self.t_active\n",
            "        \n",
            "        self.history_active.append(is_active)\n",
            "        \n",
            "        if is_active:\n",
            "            direction = self.direction_model.predict(features.reshape(1, -1))[0]\n",
            "            self.history_direction.append(direction)\n",
            "        else:\n",
            "            self.history_direction.append(None)\n",
            "            \n",
            "        # Check if we should trigger\n",
            "        if len(self.history_active) >= self.k_consecutive:\n",
            "            if all(self.history_active[-self.k_consecutive:]):\n",
            "                # We passed the Active Gate threshold. Now do Majority Vote on Direction.\n",
            "                recent_dirs = [d for d in self.history_direction[-self.m_majority:] if d is not None]\n",
            "                if len(recent_dirs) > 0:\n",
            "                    final_cmd = max(set(recent_dirs), key=recent_dirs.count)\n",
            "                    self.cooldown_counter = self.cooldown_windows\n",
            "                    return final_cmd\n",
            "        return \"NONE\"\n",
            "\n",
            "# 6. Evaluate Simulator on Held-Out Test Trials\n",
            "# We will piece back together the windows of each group to simulate a continuous stream\n",
            "test_groups_unique = np.unique(groups_test)\n",
            "\n",
            "metrics = {\n",
            "    'trials_tested': 0,\n",
            "    'true_label': [],\n",
            "    'predicted_cmd': [],\n",
            "    'latencies': [],\n",
            "    'false_triggers': 0,\n",
            "    'baseline_duration_s': 0\n",
            "}\n",
            "\n",
            "fs = 250.0\n",
            "hop_s = 0.25\n",
            "\n",
            "print(\"\\n--- Running Simulation on Held-Out Trials ---\")\n",
            "for gid in test_groups_unique:\n",
            "    mask = (groups_test == gid)\n",
            "    X_group = X_test[mask]\n",
            "    y_group = y_test_dir[mask]\n",
            "    \n",
            "    # For evaluation, what is the actual ground truth of this trial block?\n",
            "    # A group is purely Left, Right, Repeated, or Norm.\n",
            "    true_class = y_group[0]\n",
            "    metrics['trials_tested'] += 1\n",
            "    \n",
            "    # We instantiate a new decoder per trial to simulate isolated events\n",
            "    # We'll set K=2 (requires 2 consecutive 1s windows over 0.25s hops = 1.25s of data total to fire)\n",
            "    # Cooldown = 4 windows (1 second)\n",
            "    decoder = DiscreteDecoder(intent_clf, direction_clf, t_active=0.5, k_consecutive=2, cooldown_windows=4, m_majority=3)\n",
            "    \n",
            "    triggered_cmds = []\n",
            "    trigger_window_idx = []\n",
            "    \n",
            "    for i, window_features in enumerate(X_group):\n",
            "        cmd = decoder.process_window(window_features)\n",
            "        if cmd != \"NONE\":\n",
            "            triggered_cmds.append(cmd)\n",
            "            trigger_window_idx.append(i)\n",
            "            \n",
            "    if true_class in ['Left', 'Right']:\n",
            "        # We expected exactly ONE valid trigger corresponding to the true class\n",
            "        metrics['true_label'].append(true_class)\n",
            "        if len(triggered_cmds) > 0:\n",
            "            # Did it fire the CORRECT command first?\n",
            "            metrics['predicted_cmd'].append(triggered_cmds[0])\n",
            "            # Calculate latency in seconds based on window index (index * hop_s) + 1.0s window size\n",
            "            latency = (trigger_window_idx[0] * hop_s) + 1.0\n",
            "            metrics['latencies'].append(latency)\n",
            "        else:\n",
            "            metrics['predicted_cmd'].append(\"MISSED\")\n",
            "    elif true_class == 'Norm':\n",
            "        # Any trigger here is a False Positive!\n",
            "        metrics['false_triggers'] += len(triggered_cmds)\n",
            "        metrics['baseline_duration_s'] += len(X_group) * hop_s + 1.0\n",
            "\n",
            "predicted_correct = sum(1 for t, p in zip(metrics['true_label'], metrics['predicted_cmd']) if t == p)\n",
            "missed = metrics['predicted_cmd'].count(\"MISSED\")\n",
            "wrong_dir = len(metrics['true_label']) - predicted_correct - missed\n",
            "total_dir_trials = len(metrics['true_label'])\n",
            "\n",
            "print(f\"\\nTotal Left/Right Trials Tested: {total_dir_trials}\")\n",
            "print(f\"Correctly Triggered Direction: {predicted_correct} ({(predicted_correct/total_dir_trials)*100:.1f}%)\")\n",
            "print(f\"Wrong Direction Triggered: {wrong_dir} ({(wrong_dir/total_dir_trials)*100:.1f}%)\")\n",
            "print(f\"Missed (Failed to Trigger Active Gate): {missed} ({(missed/total_dir_trials)*100:.1f}%)\")\n",
            "\n",
            "if metrics['latencies']:\n",
            "    print(f\"Average Latency from Start Marker: {np.mean(metrics['latencies']):.2f}s (+/- {np.std(metrics['latencies']):.2f}s)\")\n",
            "\n",
            "print(f\"\\nTotal Baseline (Norm) Duration Simulated: {metrics['baseline_duration_s'] / 60.0:.2f} Minutes\")\n",
            "print(f\"Total False Triggers during Baseline: {metrics['false_triggers']}\")\n",
            "if metrics['baseline_duration_s'] > 0:\n",
            "    fpr_per_min = metrics['false_triggers'] / (metrics['baseline_duration_s'] / 60.0)\n",
            "    print(f\"False Trigger Rate (Commands/Minute): {fpr_per_min:.2f}\")\n",
            "\n",
            "# Print quick confusion matrix for the fired commands\n",
            "valid_preds = [(t, p) for t, p in zip(metrics['true_label'], metrics['predicted_cmd']) if p != \"MISSED\"]\n",
            "if valid_preds:\n",
            "    t_labels = [v[0] for v in valid_preds]\n",
            "    p_labels = [v[1] for v in valid_preds]\n",
            "    cm = confusion_matrix(t_labels, p_labels, labels=['Left', 'Right'])\n",
            "    print(\"\\n--- Confusion Matrix (Fired Commands Only) ---\")\n",
            "    print(\"             Predicted Left | Predicted Right\")\n",
            "    print(f\"Actual Left:       {cm[0,0]}        |       {cm[0,1]}\")\n",
            "    print(f\"Actual Right:      {cm[1,0]}        |       {cm[1,1]}\")"
        ]
    }

    nb['cells'].extend([markdown_cell, code_cell])

    with open(notebook_path, 'w') as f:
        json.dump(nb, f, indent=1)
    
    print("Step 11 added successfully.")
