import json

notebook_path = '/Users/yanivnaggar/Desktop/Spring 2026/IS/BCI-project/data_cleaning_analysis.ipynb'
with open(notebook_path, 'r') as f:
    nb = json.load(f)

# Find the last code cell
code_cells = [i for i, cell in enumerate(nb['cells']) if cell['cell_type'] == 'code']
last_idx = code_cells[-1]

new_source = [
    "import pandas as pd\n",
    "import numpy as np\n",
    "from sklearn.model_selection import StratifiedGroupKFold, cross_validate, cross_val_predict\n",
    "from sklearn.pipeline import Pipeline\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.discriminant_analysis import LinearDiscriminantAnalysis\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.svm import SVC\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay\n",
    "from sklearn.inspection import permutation_importance\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "fs = 250.0\n",
    "window_size = int(1.0 * fs)  # 250 samples\n",
    "hop_active = int(0.25 * fs)  # 62 samples (approx 75% overlap)\n",
    "\n",
    "def sliding_window_extraction_grouped(trials_list, label, start_group_id):\n",
    "    features_list = []\n",
    "    labels_list = []\n",
    "    group_ids = []\n",
    "    current_group = start_group_id\n",
    "    \n",
    "    for trial in trials_list:\n",
    "        filtered_trial = apply_filters(trial)\n",
    "        trial_length = len(filtered_trial)\n",
    "        \n",
    "        max_start = trial_length - window_size\n",
    "        start_idx = 0\n",
    "        while start_idx <= max_start:\n",
    "            window_df = filtered_trial.iloc[start_idx:start_idx + window_size]\n",
    "            feats = extract_features(window_df)\n",
    "            features_list.append(feats)\n",
    "            labels_list.append(label)\n",
    "            group_ids.append(current_group)\n",
    "            start_idx += hop_active\n",
    "            \n",
    "        current_group += 1\n",
    "        \n",
    "    return features_list, labels_list, group_ids, current_group\n",
    "\n",
    "# Extract sliding windows for Left and Right, passing the group ID state along to ensure they are unique\n",
    "feats_left, labels_left, groups_left, next_id = sliding_window_extraction_grouped(trials_left, 'Left', 0)\n",
    "feats_right, labels_right, groups_right, _ = sliding_window_extraction_grouped(trials_right, 'Right', next_id)\n",
    "\n",
    "# Build Full Left/Right Dataset\n",
    "df_sw = pd.DataFrame(feats_left + feats_right)\n",
    "X_sw = df_sw.values\n",
    "y_sw = np.array(labels_left + labels_right)\n",
    "groups_sw = np.array(groups_left + groups_right)\n",
    "\n",
    "print(f\"Sliding Window (1s, 75% overlap) Left/Right Shape: {df_sw.shape}\")\n",
    "print(f\"Distinct Original Trials (Groups): {len(np.unique(groups_sw))}\")\n",
    "\n",
    "# Train / Evaluate Models using StratifiedGroupKFold\n",
    "models = {\n",
    "    'LDA': LinearDiscriminantAnalysis(),\n",
    "    'Logistic Regression': LogisticRegression(max_iter=1000, class_weight='balanced'),\n",
    "    'SVM (RBF)': SVC(kernel='rbf', probability=True, class_weight='balanced'),\n",
    "    'Random Forest': RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')\n",
    "}\n",
    "\n",
    "cv_sw = StratifiedGroupKFold(n_splits=5)\n",
    "results_sw = {}\n",
    "\n",
    "print(\"\\n--- Left vs Right (1s Sliding Window, Grouped by Trial) ---\")\n",
    "for name, clf in models.items():\n",
    "    pipeline = Pipeline([\n",
    "        ('scaler', StandardScaler()),\n",
    "        ('classifier', clf)\n",
    "    ])\n",
    "    \n",
    "    cv_results = cross_validate(pipeline, X_sw, y_sw, groups=groups_sw, cv=cv_sw, scoring=['accuracy', 'f1_macro'])\n",
    "    y_pred = cross_val_predict(pipeline, X_sw, y_sw, groups=groups_sw, cv=cv_sw)\n",
    "    \n",
    "    results_sw[name] = {\n",
    "        'acc_mean': cv_results['test_accuracy'].mean(),\n",
    "        'acc_std': cv_results['test_accuracy'].std(),\n",
    "        'f1_mean': cv_results['test_f1_macro'].mean(),\n",
    "        'predictions': y_pred\n",
    "    }\n",
    "    \n",
    "    print(f\"{name}:\")\n",
    "    print(f\"  Accuracy: {results_sw[name]['acc_mean']:.3f} (+/- {results_sw[name]['acc_std']:.3f})\")\n",
    "    print(f\"  Macro F1: {results_sw[name]['f1_mean']:.3f}\")\n",
    "\n",
    "    # Optional: Plot Confusion Matrix\n",
    "    # cm = confusion_matrix(y_sw, y_pred, labels=['Left', 'Right'])\n",
    "    # disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Left', 'Right'])\n",
    "    # disp.plot(cmap='Blues', colorbar=False)\n",
    "    # plt.title(f\"{name} - Confusion Matrix\")\n",
    "    # plt.show()\n",
    "\n",
    "# Feature Importances\n",
    "print(\"\\n--- Feature Importances ---\")\n",
    "# 1. Random Forest Native\n",
    "rf_pipe = Pipeline([('scaler', StandardScaler()), ('classifier', RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced'))])\n",
    "rf_pipe.fit(X_sw, y_sw)\n",
    "rf_importances = rf_pipe.named_steps['classifier'].feature_importances_\n",
    "rf_feat_df = pd.DataFrame({'Feature': df_sw.columns, 'Importance': rf_importances}).sort_values(by='Importance', ascending=False).head(10)\n",
    "print(\"\\nTop 10 Features (Random Forest Native):\")\n",
    "print(rf_feat_df.to_string(index=False))\n",
    "\n",
    "# 2. Logistic Regression Permutation\n",
    "lr_pipe = Pipeline([('scaler', StandardScaler()), ('classifier', LogisticRegression(max_iter=1000, class_weight='balanced'))])\n",
    "lr_pipe.fit(X_sw, y_sw)\n",
    "lr_perm = permutation_importance(lr_pipe, X_sw, y_sw, n_repeats=10, random_state=42)\n",
    "lr_perm_df = pd.DataFrame({'Feature': df_sw.columns, 'Importance_Mean': lr_perm.importances_mean}).sort_values(by='Importance_Mean', ascending=False).head(10)\n",
    "print(\"\\nTop 10 Features (Logistic Regression Permutation):\")\n",
    "print(lr_perm_df.to_string(index=False))"
]

nb['cells'][last_idx]['source'] = new_source
nb['cells'][last_idx]['outputs'] = []
nb['cells'][last_idx]['execution_count'] = None

with open(notebook_path, 'w') as f:
    json.dump(nb, f, indent=1)
